---
title: "Clue Search"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggthemes)
library(pwr)
library(Hmisc)
```

This function transforms my graph data into the right format to run a chi-square test.
```{r custom function}
chisq_clues <- function(df, name){
  name <- enquo(name)
  
  res <- df %>%
    pivot_wider(id_cols = clue,
                names_from = !! name,
                values_from = n) %>%
    column_to_rownames(var = "clue") %>%
    chisq.test()
  
  res
}
```

```{r data, message=FALSE, warning=FALSE}
clue_search <- read_csv("Data/clue_search_data.csv") %>%
  filter(complete.cases(.))

operators <- read_csv("Data/operators.csv")

dates <- clue_search %>%
  distinct(date)

operators_by_date <- dates %>%
  full_join(operators, by = c("date" = "from")) %>%
  complete(date, operator) %>%
  group_by(operator) %>%
  fill(rank, level, faction, bonus, .direction = "down") %>%
  filter(!is.na(operator))
  

clue_search <- clue_search %>%
  left_join(operators_by_date, by = c("date", "operator_1" = "operator")) %>%
  left_join(operators_by_date, by = c("date", "operator_2" = "operator"), suffix = c("_1", "_2")) %>%
  mutate(clue = as.character(clue))

rm(dates, operators_by_date)
```

```{r generate extra variables}
clue_search <- clue_search %>%
  mutate(rhodes_island = if_else(faction_1 == "rhodes_island" | faction_2 == "rhodes_island",
                                 T,
                                 F),
         jessica = if_else(operator_1 == "Jessica" | operator_2 == "Jessica",
                           T,
                           F),
         reception_room = as.logical(reception_room)) %>%
  rowwise() %>%
  mutate(team = paste(sort(c(operator_1, operator_2)), collapse = "/")) %>%
  ungroup()
```

```{r operator combinations, message=FALSE, warning=FALSE}
clue_search %>%
  group_by(team) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(share_pc = n / sum(n) * 100,
         share_pc = round(share_pc)) %>%
  arrange(-n)
```

```{r summary stats}
clue_search %>%
  select(reception_room, rhodes_island, jessica) %>%
  pivot_longer(c(reception_room, rhodes_island, jessica),
               names_to = "variable") %>%
  group_by(variable, value) %>%
  summarise(n = n()) %>%
  pivot_wider(id_cols = variable,
              names_from = value,
              values_from = n) %>%
  mutate(Total = `FALSE` + `TRUE`)
```

# Graphs
```{r operators, message=FALSE, warning=FALSE}
data_operators <- clue_search %>%
  select(operator_1, operator_2) %>%
  pivot_longer(cols = c(operator_1, operator_2),
               values_to = "operator") %>%
  group_by(operator) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n) * 2) %>%
  arrange(-prop) %>%
  mutate(operator = factor(operator, .$operator))

p_01_operators <- data_operators %>%
  ggplot(aes(x = operator, y = prop)) +
  geom_col() +
  labs(y = "", title = "Operators Used",
       subtitle = "Per cent of clue searches",
       caption = "Source: vienne") +
  scale_y_continuous(labels = scales::percent) +
  theme_fivethirtyeight()

p_01_operators
```


```{r clue frequency, message=FALSE, warning=FALSE}
data_clue_search <- clue_search %>%
  filter(bonus_1 == 0, bonus_2 == 0) %>%
  group_by(clue) %>%
  summarise(n = n()) %>% 
  mutate(prop = n / sum(n),
         y_lower = binconf(n, sum(n))[,2],
         y_upper = binconf(n, sum(n))[,3])


caption <- paste0("n = ",
                  sum(data_clue_search$n),
                  "\nSource: vienne")

p_02_clue_share <- data_clue_search %>%
  ggplot(aes(x = clue, y = prop)) +
  geom_col() +
  labs(y = "", title = "Frequency of Clues",
       subtitle = "Operators without Clue Faction bonus",
       caption = caption) +
  scale_y_continuous(labels = scales::percent) +
  theme_fivethirtyeight()
  
  
p_02_clue_share
```

```{r rhodes island, message=FALSE, warning=FALSE}
data_rhodes_island <- clue_search %>%
  filter(bonus_1 == 0, bonus_2 == 0) %>%
  group_by(rhodes_island, clue) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  complete(rhodes_island, clue, fill = list(`n` = 0)) %>%
  group_by(rhodes_island) %>%
  mutate(prop = n / sum(n),
         y_lower = binconf(n, sum(n))[,2],
         y_upper = binconf(n, sum(n))[,3]) 



caption <- paste0("Source: vienne")

p_03_rhodes_island <- data_rhodes_island %>%
  mutate(rhodes_island = if_else(rhodes_island,
                                 "With Rhodes Island",
                                 "No Rhodes Island") %>%
           factor(levels = c("No Rhodes Island",
                             "With Rhodes Island"))) %>%
  ggplot(aes(x = clue, y = prop, fill = rhodes_island)) +
  geom_col(position = position_dodge()) +
  labs(y = "", title = "Do Rhodes Island Operators Increase Clue Seven?",
       subtitle = "Frequency of clues by operator faction",
       caption = caption) +
  scale_y_continuous(labels = scales::percent) +
  geom_errorbar(aes(ymin=y_lower, ymax=y_upper), width=.2,
                 position=position_dodge(.9)) +
  theme_fivethirtyeight() +
  ggthemes::scale_fill_fivethirtyeight() +
  theme(legend.title = element_blank())
  
p_03_rhodes_island

chisq_clues(data_rhodes_island, rhodes_island)

res <- clue_search %>%
  filter(bonus_1 == 0, bonus_2 == 0) %>%
  mutate(operators = paste(operator_1, operator_2, sep = "_")) %>%
  group_by(operators, clue) %>%
  summarise(n = n()) %>%
  ungroup() %>% 
  complete(operators, clue, fill = list(`n` = 0)) %>%
  chisq_clues(operators)

res
```

```{r reception, message=FALSE, warning=FALSE}
data_reception <- clue_search %>%
  filter(bonus_1 == 3 | bonus_2 == 3) %>%
  group_by(reception_room, clue) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  complete(reception_room, clue, fill = list(`n` = 0)) %>%
  group_by(reception_room) %>%
  mutate(prop = n / sum(n),
         y_lower = binconf(n, sum(n))[,2],
         y_upper = binconf(n, sum(n))[,3]) %>%
  ungroup()

caption <- paste0("Source: vienne")

p_04_reception <- data_reception %>%
  mutate(reception_room = if_else(reception_room,
                                  "Reception room",
                                  "Operator") %>%
           factor(levels = c("Operator", "Reception room"))) %>%
  ggplot(aes(x = clue, y = prop, fill = reception_room)) +
  geom_col(position = position_dodge()) +
  labs(y = "", title = "Do Bonuses Apply to the Reception Room?",
       subtitle = "Frequency by clue source, clue search with Jessica",
       caption = caption) +
  scale_y_continuous(labels = scales::percent) +
  geom_errorbar(aes(ymin=y_lower, ymax=y_upper), width=.2,
                 position=position_dodge(.9)) +
  theme_fivethirtyeight() +
  scale_fill_fivethirtyeight() +
  theme(legend.title = element_blank())

p_04_reception

chisq_clues(data_reception, reception_room)

# n
data_reception %>%
  group_by(reception_room) %>%
  summarise(n = sum(n))
```

```{r jessica, message=FALSE, warning=FALSE}
data_jessica <- clue_search %>%
  filter(bonus_1 %in% c(0, 3), bonus_2 %in% c(0, 3)) %>%
  group_by(jessica, clue) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  complete(jessica, clue, fill = list(`n` = 0)) %>%
  group_by(jessica) %>%
  mutate(prop = n / sum(n),
         y_lower = binconf(n, sum(n))[,2],
         y_upper = binconf(n, sum(n))[,3]) 


caption <- paste0("Source: vienne")

p_05_jessica <- data_jessica %>%
  mutate(jessica = if_else(jessica,
                           "Jessica",
                           "No clue bonus") %>%
           factor(levels = c("No clue bonus",
                             "Jessica"))) %>%
  ggplot(aes(x = clue, y = prop, fill = jessica)) +
  geom_col(position = position_dodge()) +
  labs(y = "", title = "The Effect of Jessica",
       subtitle = "Frequency of clues by operator type",
       caption = caption) +
  scale_y_continuous(labels = scales::percent) +
  geom_errorbar(aes(ymin=y_lower, ymax=y_upper), width=.2,
                 position=position_dodge(.9)) +
  theme_fivethirtyeight() +
  ggthemes::scale_fill_fivethirtyeight() +
  theme(legend.title = element_blank())
  
p_05_jessica

chisq_clues(data_jessica, jessica)
```

```{r hypothesis test equal probabilities}
clues <- data_clue_search$n
res <- chisq.test(clues)
res

# statistical power
pwr.chisq.test(w = 0.5, df = (7-1), sig.level = 0.05, power = 0.8)
pwr.chisq.test(w = 0.2, df = (7-1), sig.level = 0.05, power = 0.8)

pwr.2p.test(h = ES.h(1/7, .4), power = .8)
```

```{r team}
data_team <- clue_search %>% 
  group_by(team, clue) %>%
  summarise(n = n()) %>%
  filter(team %in% c("Gitano/Rope",
                     "Gitano/Shirayuki",
                     "Rope/Shirayuki")) %>%
  mutate(prop = n / sum(n),
         y_lower = binconf(n, sum(n))[,2],
         y_upper = binconf(n, sum(n))[,3]) 


p_06_team <- data_team %>%
  ggplot(aes(x = clue, y = prop, fill = team)) +
  geom_col(position = position_dodge()) +
  labs(y = "", title = "Operator Teams",
       subtitle = "Frequency of clues by operator team",
       caption = caption) +
  scale_y_continuous(labels = scales::percent) +
  geom_errorbar(aes(ymin=y_lower, ymax=y_upper), width=.2,
                 position=position_dodge(.9)) +
  theme_fivethirtyeight() +
  theme(legend.title = element_blank())

res <- chisq_clues(data_team, team)

p_06_team
res
```
```{r export graphs, message=FALSE, warning=FALSE}
dir.create("Graphs")

mylist <- mget(ls(pattern = "p_"))

walk2(paste0("Graphs/", names(mylist), ".png"),
      mylist,
      ggsave,
      units = "in",
      width = 7.3,
      height = 432/700 * 7.3,
      dpi = 300)
```
